config/routes.rb
Rails.application.routes.draw do
 
  get 'posts/index'

  get 'posts/edit'

  resources :statuses
  resources :documents do
     resources :comments
   end

  get 'users/index'

  get 'users/show'

  devise_for :users
  root 'dashboard#index'

  resources :users , only: [] do
    member do 
      get 'api_token'
    end
  end

        namespace :api do
          namespace :v1 do
            resources :users
            resources :documents do
           resources :comments
          end
        end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :document
  belongs_to :office

  validates :fromOffice, presence: true
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
 # before_action :authenticate_user!, except:[:index]
 before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @document = Document.find(params[:document_id])
    @comments = @document.comments.all.order('created_at Desc')
    render json: {status: 'SUCCESS', message: 'Loaded @comments', data: @comments}, status: :ok
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @document = Document.find(params[:document_id])
      @comment = @document.comments.find(params[:id])
      render json: {status: 'SUCCESS', message: 'Loaded @comment', data: @comment}, status: :ok
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:document_id, :status, :reason, :fromOffice, :office_id, :status_flag)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 # before_action :authenticate_user!, except:[:index]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @document = Document.find(params[:document_id])
    @comments = @document.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
   if user_signed_in?
    @document=Document.find(params[:document_id])
    @comment = @document.comments.new
  else
    redirect_to new_user_session_path
    end
    
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @document = Document.find(params[:document_id])
    @comment =@document.comments.update(:status_flag => true)
    @comment =@document.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to document_comments_path(@document), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location:document_comments_path(@document) }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @document = Document.find(params[:document_id])
      @comment = @document.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:document_id, :status, :reason, :fromOffice, :office_id, :status_flag)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@document, @document.comments.build], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :document_id %>
   <strong> <%= @document.series %> <%= @document.year %> <%= @document.registrationNo %> </strong> 
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_area :status, id: :comment_status %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_area :reason, id: :comment_reason %>
  </div>

  <div>
     <%= form.label :fromOffice %>
     <%= form.text_field :fromOffice, class: 'form-control', value: current_user.office.office_name, readonly: true %>
  </div><br>

    <div class="form-group">
    <%= form.label :office_id, "Office To post Document To:" %>
    <%= form.collection_select :office_id, Office.order(:office_name), :id, :office_name, include_blank: true , class: "form-control", prompt:"Select Next Office" %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th>Status</th>
      <th>Reason</th>
      <th>Fromoffice</th>
      <th>Tooffice</th>
      <th>Date Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.document.series %> <%= comment.document.year %> <%= comment.document.registrationNo %></td>
        <td><%= comment.status %></td>
        <td><%= comment.reason %></td>
        <td><%= comment.fromOffice %></td>
        <td><%= comment.office.office_name %></td>
        <td><%= comment.created_at %></td>
        <td><%= link_to 'Show', document_path(comment.document_id) %></td>
     <!--    <td><%#= link_to 'Show',  document_comment_path(@document,@comment) %></td>
        <td><%#= link_to 'Edit',  edit_document_comment_path(@comment) %></td>
        <td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% unless current_user.office_id == 13 %>

  <%= link_to 'New Comment', new_document_comment_path %> 
<%end%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', document_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @comment.document %>
</p>

<p>
  <strong>Status:</strong>
  <%= @comment.status %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @comment.reason %>
</p>

<p>
  <strong>Fromoffice:</strong>
  <%= @comment.fromOffice %>
</p>

<p>
  <strong>Tooffice:</strong>
  <%= @comment.toOffice %>
</p>

<p>
  <strong>Created Date:</strong>
  <%= @comment.created_at %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>