config/routes.rb
Rails.application.routes.draw do
 
  get 'posts/index'

  get 'posts/edit'

  resources :statuses
  resources :documents do
     resources :comments
   end

  get 'users/index'

  get 'users/show'

  devise_for :users
  root 'dashboard#index'

  resources :users , only: [] do
    member do 
      get 'api_token'
    end
  end

        namespace :api do
          namespace :v1 do
            resources :users
            resources :documents do
           resources :comments
          end
        end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         #, :validatable, :jwt_authenticatable,jwt_revocation_strategy: JWTBlacklist
         belongs_to :office


         after_create :generate_api_token

         private
         def generate_api_token
         	self.api_token = Devise.friendly_token
         	self.save
         end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

	  	def index
		  	@users = User.all.order('created_at Desc')
		  	render json: {status: 'SUCCESS', message: 'Loaded @users', data: @users}, status: :ok
		 end

	def show
	  	@user=User.find_by(:id => params[:id])
	  	#current_user.email = @user.email
	  	#if current_user.office_id == 13
	  	#@documents = Document.find_by(:email => params[:email])#.order('created_at Desc')
	  	@documents = Document.where(:email => params[:email])
	    #else
		#@comments = Comment.where(:office_id => current_user.office_id && status_flag: false).order(:created_at => :desc)
		#Client.where("orders_count = ? AND locked = ?", params[:orders], false)
		#@comments = Comment.where("office_id = ? AND status_flag = ?" , current_user.office_id , false).order(:created_at => :desc)
		#@documents = Document.where(:id  => @comments.id)
		#end
		render json: {status: 'SUCCESS', message: 'Loaded @documents', data: @documents}, status: :ok
	end

	private

			def document_params
      params.require(:document).permit(:series, :year, :registrationNo, :CandidateRange, :request, :attachment, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  	@users= User.all.order("created_at DESC")
  end

  def show
    #@user=User.find_by(:id => params[:id])
   
    if current_user.office.office_name == "Guest" 
      
  	   @documents = Document.where(:email => current_user.email).order('created_at Desc')
    else
      binding.pry
	#@comments = Comment.where(:office_id => current_user.office_id && status_flag: false).order(:created_at => :desc)
	#Client.where("orders_count = ? AND locked = ?", params[:orders], false)
	 @comments = Comment.where("office_id = ? AND status_flag = ?" , current_user.office_id , false).order(:created_at => :desc)
	#@documents = Document.where(:id  => @comments.id)
    end
  end

  def api_token
    @user=User.find(params[:id])
    respond_to do |format|
      format.json {render :json => @user.api_token, :status => :ok}
      format.html {}
    #render json: {status: 'SUCCESS', message: 'Loaded @user', data: @user}, status: :ok
    #render html: {}
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/api_token.html.erb
<h1>

<h1>Your API Token is : <%= @user.api_token%></h1>

app/views/users/index.html.erb
<h1>All Users</h1>

<table class="table">
<tr>
	<th>User Name</th>
	<th>User Email </th>
	<th>User Office</th>
	
</tr>

<tbody>
	<% @users.each do |user| %>
	<tr>
		<td> <%= user.fullName %></td>
	 <td> <%= user.email %></td>
	 <td> <%= user.office.office_name %></td>
	 <td><%= link_to 'Users', users_show_path, :class => 'navbar-link' %></td>
	 
	</tr>
</tbody>
<% end -%>
</table>

app/views/users/show.html.erb
<h1>User's Profile</h1>

<%if current_user.office.office_name == "Guest" %>
<p id="notice"><%= notice %></p>

<h3> Welcome ! , underlisted are your created Documents :</h3>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Series</th>
      <th>Year</th>
      <th>Registrationno</th>
      <th>Candidaterange</th>
      <th>Request</th>
      <th>Attachment</th>
      <th>Email</th>
      <th>Created Date:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.series %></td>
        <td><%= document.year %></td>
        <td><%= document.registrationNo %></td>
        <td><%= document.CandidateRange %></td>
        <td><%= document.request %></td>
        <td><%= document.attachment %></td>
        <td><%= document.email %></td>
        <td><%= document.created_at %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

<% else %>

<p id="notice"><%= notice %></p>

<h3> Welcome ! , underlisted are Documents presently in your Department  :</h3>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th>Status</th>
      <th>Reason</th>
      <th>Fromoffice</th>
      <th>Tooffice</th>
      <th>Date Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.document.series %> <%= comment.document.year %> <%= comment.document.registrationNo %></td>
        <td><%= comment.status %></td>
        <td><%= comment.reason %></td>
        <td><%= comment.fromOffice %></td>
        <td><%= comment.office.office_name %></td>
        <td><%= comment.created_at %></td>
        <td><%= link_to 'Show', document_path(comment.document_id) %></td>
     <!--    <td><%#= link_to 'Show',  document_comment_path(@document,@comment) %></td>
        <td><%#= link_to 'Edit',  edit_document_comment_path(@comment) %></td>
        <td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end %>