config/routes.rb
Rails.application.routes.draw do
 
  get 'posts/index'

  get 'posts/edit'

  resources :statuses
  resources :documents do
     resources :comments
   end

  get 'users/index'

  get 'users/show'

  devise_for :users
  root 'dashboard#index'

  resources :users , only: [] do
    member do 
      get 'api_token'
    end
  end

        namespace :api do
          namespace :v1 do
            resources :users
            resources :documents do
           resources :comments
          end
        end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :statuses
  has_many :comments, dependent: :destroy

 #before_save :save_default_value_on_create, :if => :new_record?

  private

  def save_default_value_on_create
  	
  		if @document.series =='MJ' 
  			@document.office_id = 1
  			@document.action = 'Posted'
  			@document.reason = 'Posted'
  		
  	    elsif
  		 @document.series =='ND' 
  			@document.office_id = 2
  			@document.action = 'Posted'
  			@document.reason = 'Posted'
  		end
  	end

end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController

	def index
    @user=User.find_by(:id => params[:id])
      @documents = Document.find_by(:email => params[:email])
    #@documents = Document.all.order("created_at DESC")
    render json: {status: 'SUCCESS', message: 'Loaded @documents', data: @documents}, status: :ok
  	end


	def show
     # @document = Document.find(params[:id]) 
                          sql = <<-SQL 
                                      SELECT a.series, a.year, a."registrationNo", a."CandidateRange", a.request, a.email, a.created_at,
                                             b.status, b.reason, b."fromOffice", c.office_name, b.status_flag
                                      FROM documents As a
                                      inner join comments As b
                                      on a.id = b.document_id
                                      inner join offices as c
                                      on c.id = b.office_id
                                      where a.id = '#{params[:id]}'
                                      SQL

                                    @document = ActiveRecord::Base.connection.exec_query(sql)
           
    
      render json: {status: 'SUCCESS', message: 'Loaded @document', data: @document}, status: :ok
    end

	private

	def document_params
      params.require(:document).permit(:series, :year, :registrationNo, :CandidateRange, :request, :attachment, :email)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all.order("created_at DESC")
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @user=User.find_by(:id => params[:id])
      @documents = Document.where(:email => current_user.email)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save 
        #Status.create(document_id: @document.id, arrivalFrom: current_user.office.office_name)
        #@document = Document.find(params[:document_id])
       #@comment =@document.comments.create(document_id: @document.id, fromOffice: current_user.office.office_name)
        if @document.series == "MJ" || @document.series=="SC"
           #@comment.office_id = 1
            Comment.create(document_id: @document.id, fromOffice: current_user.office.office_name, office_id: 1)
       else
         #@comment.office_id = 2 
         Comment.create(document_id: @document.id, fromOffice: current_user.office.office_name, office_id: 2)     
        end

        #Comment.create(document_id: @document.id, fromOffice: current_user.office.office_name)
        #status_onCreate_document
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:series, :year, :registrationNo, :CandidateRange, :request, :attachment, :email)
    end

    def comment_params
       params.require(:comment).permit(:document_id, :status, :reason, :fromOffice, :office_id, :status_flag)
    end

    def status_params
      params.require(:status).permit(:document_id, :action, :reason, :arrivalFrom, :postedTo)
    end

    def self.status_onCreate_document

      Status.create(document_id: @document.id, action: status.action, reason:status.reason, arrivalFrom: current_user.office.office_name,
        postedTo: status.postedTo)
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   <%= form.label :series %>
  <%= form.select :series, options_for_select([['Select Exam Series'],['June' ,'MJ'], ['December', 'ND'], ['School Candidate', 'SC'], ['Private Candidate', 'PC']]) %>
  </div><br>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :document_year %>
  </div>

  <div class="field">
    <%= form.label :registrationNo,"Centre No. / Candidate Full Registration No" %>
    <%= form.text_field :registrationNo, id: :document_registrationNo %>
  </div>

  <div class="field">
    <%= form.label :CandidateRange, "Specify Candidate Range" %>
    <%= form.text_field :CandidateRange, id: :document_CandidateRange %>
  </div>

  <div class="field">
    <%= form.label :request %>
    <%= form.text_area :request, id: :document_request %>
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.text_area :attachment, id: :document_attachment %>
  </div>

  <div class="field">
    <%= form.label :email,"Applicant's Email:" %>
    <%= form.text_field :email, id: :document_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Series</th>
      <th>Year</th>
      <th>Registrationno</th>
      <th>Candidaterange</th>
      <th>Request</th>
      <th>Attachment</th>
      <th>Email</th>
      <th>Created Date:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.series %></td>
        <td><%= document.year %></td>
        <td><%= document.registrationNo %></td>
        <td><%= document.CandidateRange %></td>
        <td><%= document.request %></td>
        <td><%= document.attachment %></td>
        <td><%= document.email %></td>
        <td><%= document.created_at %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Series:</strong>
  <%= @document.series %>
</p>

<p>
  <strong>Year:</strong>
  <%= @document.year %>
</p>

<p>
  <strong>Registrationno:</strong>
  <%= @document.registrationNo %>
</p>

<p>
  <strong>Candidaterange:</strong>
  <%= @document.CandidateRange %>
</p>

<p>
  <strong>Request:</strong>
  <%= @document.request %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @document.attachment %>
</p>

<p>
  <strong>Email:</strong>
  <%= @document.email %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Document Processing Status', document_comments_path(@document) %> |
<%= link_to 'Back', documents_path %>