config/routes.rb
Rails.application.routes.draw do
 
  get 'posts/index'

  get 'posts/edit'

  resources :statuses
  resources :documents do
     resources :comments
   end

  get 'users/index'

  get 'users/show'

  devise_for :users
  root 'dashboard#index'

  resources :users , only: [] do
    member do 
      get 'api_token'
    end
  end

        namespace :api do
          namespace :v1 do
            resources :users
            resources :documents do
           resources :comments
          end
        end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.fullName %></strong> | <%= current_user.email %>| <strong><%= current_user.office.office_name %></strong>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
  <%= link_to 'Users', users_index_path, :class => 'navbar-link' %> |
  <%= link_to 'profile', users_show_path, :class => 'navbar-link' %> |
  <%= link_to 'Home', root_path, :class => 'navbar-link' %> |
  <%= link_to 'Documents', documents_path, :class => 'navbar-link' %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>